### ISSUE TITLE
ConcatConv2D explanation

### ISSUE THREAD

**Issue by philipperemy** [Lingkai-Kong/SDE-Net#5]
Can you explain what did you want to achieve here?

https://github.com/Lingkai-Kong/SDE-Net/blob/a69a7e35d0a1b509761795bd69f67066781d674b/MNIST/models/sdenet_mnist.py#L62

Is it just to add the time t as a feature to the CNN layer?

Thanks!

**Comment by Lingkai-Kong** [comment]
Yes. f(x,t) is also a function of t. Therefore, we use the time as an additional channel.

**Comment by philipperemy** [comment]
Ok thank you. Looks good.
